### ISSUE TITLE
Highlighting examples

### ISSUE THREAD

**Issue by jorgeramirez** [TrentoCrowdAI/servant-api#4]
- Use CSV files instead of fixed content (AMT)
- Implement it on Toloka.
- Interface alternative where each of the sentences has a checkbox in front. (F8)

**Comment by simonedegiacomi** [comment]
>     * Use CSV files instead of fixed content (AMT)

In AMT it's not possible to select the number of questions as a simple number (like it's possible with F8 and Toloka): you need to manually copy and paste the HTML of the layout and use different variables (for example ${paper_title_1} and ${paper_title_2}).
Given that the tasks of this issues are proof of concepts, I adapted the code to show a single question from csv data.

>     * Implement it on Toloka.
>     * Interface alternative where each of the sentences has a checkbox in front. (F8)

Is it ok if I create the example files in the repository or it's better to upload them as Gist and put the links here?

**Comment by jorgeramirez** [comment]
> > ```
> > * Use CSV files instead of fixed content (AMT)
> > ```
> 
> In AMT it's not possible to select the number of questions as a simple number (like it's possible with F8 and Toloka): you need to manually copy and paste the HTML of the layout and use different variables (for example ${paper_title_1} and ${paper_title_2}).
> Given that the tasks of this issues are proof of concepts, I adapted the code to show a single question from CSV data.

Alright, cool. Then this is something we would keep an eye on in the future when we want to publish using the notion of many items per page and multiple pages (AMT does not have this structure).


> 
> > ```
> > * Implement it on Toloka.
> > * Interface alternative where each of the sentences has a checkbox in front. (F8)
> > ```
> 
> Is it ok if I create the example files in the repository or it's better to upload them as Gist and put the links here?

Yes, you can put your examples in a folder inside src. Maybe calling it "highlighting-demos".

**Comment by jorgeramirez** [comment]
@simonedegiacomi after you complete a tiny version of the highlighting examples for each platform, you can prepare a highlighting example for AMT that uses the CSVs. The idea is to use the Qualifications that AMT offers to define the test questions that workers need to pass to perform the HIT (in terms of F8 this will be the first page where we only show test questions).

https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/Concepts_QualificationsArticle.html#qualification-tests

**Comment by simonedegiacomi** [comment]
@jorgeramirez I read the documentation about qualification types and I found out that there are two ways to give qualifications to workers:
- Specifying a test question and a right answer while creating the QualificationType: doing this, when the worker answers correctly to the test question the system automatically gives the qualification to the worker;
- Specifying the flag AutoGranted to true: doing this AMT will automatically give the qualification. Since qualifications have a value attribute (an integer that ranges from 0 to 100), it is possible to set the AutoGrantedValue to 0 and then increment this value using the API;

The first option seems similar to the options of the other platforms, but it has a big limitation: the test question can be specified only using the [QuestionForm](https://docs.aws.amazon.com/en_us/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QuestionFormDataStructureArticle.html) format. This means that, if we want to create a test question for a Job that requires custom HTML (like highlighting, where the [HTMLQuestion](https://docs.aws.amazon.com/en_us/AWSMechTurk/latest/AWSMturkAPI/ApiReference_HTMLQuestionArticle.html) format is used) we need to use the second method.

For example, for a QualificationType that certifies the ability of a worker to highlight some part of text, we would need to:
1. Create the qualification type specifying AutoGranted to true and AutoGrantedValue to 0;
2. Create an AMT HIT that uses golden data and requires a value of our qualification type equal to 0;
3. Download the results for the AMT HIT and call the API to increment the value associated to the qualification.

This method has the disadvantage that the HIT must reward the worker.

(If the test we want to use to automatically assign a qualification requires the highlighting of some text, maybe we can replace the highlighting with the alternative layout, using the checkboxes. I didn't try it, but I think that it is possibile to create a test of this kind using the QuestionForm format).
